//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLangExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserLangExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NotepadPlus&gt;
        ///    &lt;UserLang name=&quot;MRILang&quot; ext=&quot;&quot;&gt;
        ///        &lt;Settings&gt;
        ///            &lt;Global caseIgnored=&quot;yes&quot; /&gt;
        ///            &lt;TreatAsSymbol comment=&quot;no&quot; commentLine=&quot;no&quot; /&gt;
        ///            &lt;Prefix words1=&quot;no&quot; words2=&quot;no&quot; words3=&quot;no&quot; words4=&quot;no&quot; /&gt;
        ///        &lt;/Settings&gt;
        ///        &lt;KeywordLists&gt;
        ///            &lt;Keywords name=&quot;Delimiters&quot;&gt;[&amp;apos;0]&amp;apos;0&lt;/Keywords&gt;
        ///            &lt;Keywords name=&quot;Folder+&quot;&gt;&lt;/Keywords&gt;
        ///            &lt;Keywords name=&quot;Folder-&quot;&gt;&lt;/Keywords&gt;
        ///            &lt;Keywords name=&quot;Operators&quot;&gt;- ( ) * , / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string userDefineLang {
            get {
                return ResourceManager.GetString("userDefineLang", resourceCulture);
            }
        }
    }
}
